server:
  port: ${SERVER_PORT:8080}
app:
  base-url: ${APP_BASE_URL:http://localhost:${SERVER_PORT:8080}}
  token:
    expiry-minutes: 10

upload:
  path: uploads/thumbnails/

spring:
  application:
    name: DonationManagement
  security:
    user:
      name: admin
      password: "{noop}123456"
  datasource:
    url:
      ${MYSQL_URL:jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/donation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#PayOS
payos:
  client-id: 967ec853-0047-4cec-bebc-1d8aea69d993
  api-key: d250c5f7-358a-403f-a637-0a3ea0c8121a
  checksum-key: d111fe080f69f53c6753bdbe65c3278e866cf2d44cbb934ffcca6b741d60b1c8
  return-url: ${app.base-url}/thanh-toan/thanh-cong
  cancel-url: ${app.base-url}/thanh-toan/that-bai
